Feat/pagination metadata
unepwcmc/ocean-plus-habitats pull request #231
Opened 2022-11-28 08:44 UTC by WillKocur

Adds metadata to the index countries endpoint

2022-11-28 11:47 UTC, sergiomarrocoli requested changes
looks good. spec is broken but i think you already fixed them in the other PR. two minor comments, but otherwise happy to approve

2022-11-28 11:47 UTC, sergiomarrocoli commented on app/controllers/api/v1/countries_controller.rb
> +    @countries.count
could memoize or use ```.length``` here to avoid a database call

2022-11-28 11:47 UTC, sergiomarrocoli commented on app/controllers/api/v1/countries_controller.rb
> +    25
unless we're allowing a param here, should probably be a constant rather than a method

2022-11-28 12:29 UTC, sergiomarrocoli commented on app/controllers/api/v1/countries_controller.rb
> +    @countries.count
could memoize with ```@total_count ||= @countries.count```

2022-11-28 12:33 UTC, sergiomarrocoli requested changes
left a comment about memoization

2022-11-29 15:46 UTC, WillKocur commented
> left a comment about memoization

All done - thanks!

2022-11-30 09:10 UTC, sergiomarrocoli approved these changes

2022-11-30 09:24 UTC, merged